### PR TITLE
Allow math to be used for thresholds

### PR DESCRIPTION
**Pull request by sillyfrog**
This supports sorting the thresholds based on the current values calculated for the thresholds if a math based value is used.

### CODE REVIEW

**Comment by sillyfrog** [comment]
This one is further to the other PR to handle sorting correctly based on the current value. GitHub was having some issues when I first tried to merge the PR, however it appears to be working now.
Let me know what you think and if it's something you're up for merging. Cheers!

**Comment by sillyfrog** [comment]
@jfoxe - this PR now includes support for Math in min and max. You can pull from my repo until this is merged. :)

**Comment by jfoxe** [comment]
@sillyfrog Thanks! works like a charm!

**Comment by mserna** [comment]
@sillyfrog Can you merge into my developing branch for singlestat-math, so I can test to ensure that everything works correctly. If everything looks good then I'll ask blackmirror to merge into master with your changes as well. :)

**Comment by sillyfrog** [comment]
> @sillyfrog Can you merge into my developing branch for singlestat-math, so I can test to ensure that everything works correctly. If everything looks good then I'll ask blackmirror to merge into master with your changes as well. :)

I'll get to it as soon as I can, it maybe a couple of day, but I'm on it. Cheers!

**Comment by sillyfrog** [comment]
Sorry all, totally dropped the ball on this. I have now created another PR #30 that should merge cleanly. @mserna Since I took so long it looks like your dev branch has gone, so going back to merging to master - let me know if you want me to send it elsewhere.
Thanks!

**Pull request closed without merging**
